import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from './ui/dialog';
import { Plus, Calendar, DollarSign, Users, TrendingUp, Edit2, Trash2, CheckCircle, Clock, Sparkles, QrCode, Download, ExternalLink } from 'lucide-react';
import QRCodeDisplay from './QRCodeDisplay';

interface Event {
  id: number;
  name: string;
  date: string;
  budget: number;
  actualCost?: number;
  revenue?: number;
  expectedAttendees: number;
  actualAttendees?: number;
  status: 'Draft' | 'Planning' | 'Ready' | 'Completed';
  category: string;
  description: string;
  venue?: string;
  autoGeneratedTasks?: boolean;
}

interface AutoTask {
  title: string;
  description: string;
  assignee: string;
  dueDate: string;
  priority: 'High' | 'Medium' | 'Low';
  category: string;
}

const EVENTS_STORAGE_KEY = 'clubhub-events';

export default function Events() {
  const [events, setEvents] = useState<Event[]>(() => {
    if (typeof window === 'undefined') return [
    {
      id: 1,
      name: 'Spring Fundraiser',
      date: '2026-03-20',
      budget: 2500,
      actualCost: 2400,
      revenue: 8500,
      expectedAttendees: 100,
      actualAttendees: 95,
      status: 'Planning',
      category: 'Fundraising',
      description: 'Annual spring fundraiser with auction and dinner',
      autoGeneratedTasks: true
    },
    {
      id: 2,
      name: 'Networking Mixer',
      date: '2026-03-28',
      budget: 800,
      expectedAttendees: 75,
      status: 'Ready',
      category: 'Networking',
      description: 'Professional networking event with industry speakers',
      venue: 'Student Center Room 301',
      autoGeneratedTasks: true
    },
    {
      id: 3,
      name: 'Winter Gala',
      date: '2025-12-10',
      budget: 1500,
      actualCost: 1500,
      revenue: 5200,
      expectedAttendees: 100,
      actualAttendees: 120,
      status: 'Completed',
      category: 'Social',
      description: 'Annual winter gala celebration with ticket sales',
      venue: 'Grand Ballroom',
      autoGeneratedTasks: true
    },
    {
      id: 4,
      name: 'Game Night',
      date: '2026-02-15',
      budget: 300,
      actualCost: 275,
      expectedAttendees: 50,
      actualAttendees: 58,
      status: 'Completed',
      category: 'Social',
      description: 'Casual game night for members - free event',
      venue: 'Student Lounge',
      autoGeneratedTasks: true
    },
    {
      id: 5,
      name: 'Study Workshop',
      date: '2026-01-20',
      budget: 200,
      actualCost: 180,
      expectedAttendees: 30,
      actualAttendees: 35,
      status: 'Completed',
      category: 'Educational',
      description: 'Free workshop with study resources and snacks',
      venue: 'Library Room 205',
      autoGeneratedTasks: true
    },
  ];

    try {
      const stored = window.localStorage.getItem(EVENTS_STORAGE_KEY);
      return stored ? (JSON.parse(stored) as Event[]) : [
        {
          id: 1,
          name: 'Spring Fundraiser',
          date: '2026-03-20',
          budget: 2500,
          actualCost: 2400,
          revenue: 8500,
          expectedAttendees: 100,
          actualAttendees: 95,
          status: 'Planning',
          category: 'Fundraising',
          description: 'Annual spring fundraiser with auction and dinner',
          autoGeneratedTasks: true,
        },
        {
          id: 2,
          name: 'Networking Mixer',
          date: '2026-03-28',
          budget: 800,
          expectedAttendees: 75,
          status: 'Ready',
          category: 'Networking',
          description: 'Professional networking event with industry speakers',
          venue: 'Student Center Room 301',
          autoGeneratedTasks: true,
        },
        {
          id: 3,
          name: 'Winter Gala',
          date: '2025-12-10',
          budget: 1500,
          actualCost: 1500,
          revenue: 5200,
          expectedAttendees: 100,
          actualAttendees: 120,
          status: 'Completed',
          category: 'Social',
          description: 'Annual winter gala celebration with ticket sales',
          venue: 'Grand Ballroom',
          autoGeneratedTasks: true,
        },
        {
          id: 4,
          name: 'Game Night',
          date: '2026-02-15',
          budget: 300,
          actualCost: 275,
          expectedAttendees: 50,
          actualAttendees: 58,
          status: 'Completed',
          category: 'Social',
          description: 'Casual game night for members - free event',
          venue: 'Student Lounge',
          autoGeneratedTasks: true,
        },
        {
          id: 5,
          name: 'Study Workshop',
          date: '2026-01-20',
          budget: 200,
          actualCost: 180,
          expectedAttendees: 30,
          actualAttendees: 35,
          status: 'Completed',
          category: 'Educational',
          description: 'Free workshop with study resources and snacks',
          venue: 'Library Room 205',
          autoGeneratedTasks: true,
        },
      ];
    } catch {
      return [
        {
          id: 1,
          name: 'Spring Fundraiser',
          date: '2026-03-20',
          budget: 2500,
          actualCost: 2400,
          revenue: 8500,
          expectedAttendees: 100,
          actualAttendees: 95,
          status: 'Planning',
          category: 'Fundraising',
          description: 'Annual spring fundraiser with auction and dinner',
          autoGeneratedTasks: true,
        },
      ];
    }
  });

  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState<Event | null>(null);
  const [qrCodeEvent, setQrCodeEvent] = useState<Event | null>(null);

  useEffect(() => {
    try {
      window.localStorage.setItem(EVENTS_STORAGE_KEY, JSON.stringify(events));
    } catch {
      // ignore
    }
  }, [events]);
  
  // Form state
  const [formData, setFormData] = useState<Partial<Event>>({
    status: 'Draft',
    category: 'Social'
  });

  const eventCategories = ['Social', 'Fundraising', 'Networking', 'Educational', 'Community Service', 'Competition'];
  const boardMembers = ['Sarah Chen', 'Mike Johnson', 'Emma Davis', 'Alex Brown', 'Jessica Lee', 'David Kim', 'Rachel Martinez', 'Tom Anderson'];

  // Auto-generate tasks based on event
  const generateEventTasks = (event: Partial<Event>): AutoTask[] => {
    const eventDate = new Date(event.date || new Date());
    const tasks: AutoTask[] = [];

    // Calculate task due dates
    const sixWeeksBefore = new Date(eventDate);
    sixWeeksBefore.setDate(eventDate.getDate() - 42);
    
    const fourWeeksBefore = new Date(eventDate);
    fourWeeksBefore.setDate(eventDate.getDate() - 28);
    
    const twoWeeksBefore = new Date(eventDate);
    twoWeeksBefore.setDate(eventDate.getDate() - 14);
    
    const oneWeekBefore = new Date(eventDate);
    oneWeekBefore.setDate(eventDate.getDate() - 7);
    
    const threeDaysBefore = new Date(eventDate);
    threeDaysBefore.setDate(eventDate.getDate() - 3);

    // Generate standard event tasks
    tasks.push({
      title: `Book venue for ${event.name}`,
      description: `Research and secure venue for ${event.name}`,
      assignee: 'Mike Johnson',
      dueDate: sixWeeksBefore.toISOString().split('T')[0],
      priority: 'High',
      category: 'Events'
    });

    tasks.push({
      title: `Create marketing materials for ${event.name}`,
      description: `Design flyers, social media posts, and promotional content`,
      assignee: 'Sarah Chen',
      dueDate: fourWeeksBefore.toISOString().split('T')[0],
      priority: 'High',
      category: 'Marketing'
    });

    tasks.push({
      title: `Send event invitations for ${event.name}`,
      description: `Email invitations and update event registration page`,
      assignee: 'Emma Davis',
      dueDate: fourWeeksBefore.toISOString().split('T')[0],
      priority: 'Medium',
      category: 'Communications'
    });

    if (event.category === 'Fundraising') {
      tasks.push({
        title: `Secure sponsors for ${event.name}`,
        description: `Contact and confirm sponsors, prepare sponsorship packets`,
        assignee: 'Alex Brown',
        dueDate: fourWeeksBefore.toISOString().split('T')[0],
        priority: 'High',
        category: 'Finance'
      });
    }

    tasks.push({
      title: `Finalize event logistics for ${event.name}`,
      description: `Confirm catering, AV equipment, seating arrangements`,
      assignee: 'Jessica Lee',
      dueDate: twoWeeksBefore.toISOString().split('T')[0],
      priority: 'High',
      category: 'Events'
    });

    tasks.push({
      title: `Create check-in system for ${event.name}`,
      description: `Set up registration table, name tags, attendee tracking`,
      assignee: 'David Kim',
      dueDate: oneWeekBefore.toISOString().split('T')[0],
      priority: 'Medium',
      category: 'Operations'
    });

    tasks.push({
      title: `Final walkthrough for ${event.name}`,
      description: `Visit venue, test equipment, review timeline`,
      assignee: 'Mike Johnson',
      dueDate: threeDaysBefore.toISOString().split('T')[0],
      priority: 'High',
      category: 'Events'
    });

    return tasks;
  };

  // Auto-calculate metrics
  const calculateEventMetrics = (event: Event) => {
    const roi = event.revenue && event.actualCost ? (event.revenue / event.actualCost).toFixed(2) : 'N/A';
    const profit = event.revenue && event.actualCost ? event.revenue - event.actualCost : 'N/A';
    const successRate = event.actualAttendees && event.expectedAttendees 
      ? ((event.actualAttendees / event.expectedAttendees) * 100).toFixed(0) 
      : 'N/A';
    
    return { roi, profit, successRate };
  };

  const handleAddEvent = () => {
    if (!formData.name || !formData.date || !formData.budget || !formData.expectedAttendees) {
      alert('Please fill in all required fields');
      return;
    }

    const newEvent: Event = {
      id: events.length + 1,
      name: formData.name,
      date: formData.date,
      budget: Number(formData.budget),
      expectedAttendees: Number(formData.expectedAttendees),
      status: formData.status || 'Draft',
      category: formData.category || 'Social',
      description: formData.description || '',
      venue: formData.venue,
      autoGeneratedTasks: true
    };

    setEvents([...events, newEvent]);
    
    // Generate tasks automatically
    const autoTasks = generateEventTasks(newEvent);
    console.log('Auto-generated tasks:', autoTasks);
    // In a real app, these would be added to the tasks state

    setIsAddDialogOpen(false);
    setFormData({ status: 'Draft', category: 'Social' });
    
    // Show success message
    alert(`Event "${newEvent.name}" created successfully!\n${autoTasks.length} tasks automatically generated.`);
  };

  const handleUpdateEvent = () => {
    if (!selectedEvent) return;

    const updatedEvents = events.map(event => 
      event.id === selectedEvent.id ? { ...selectedEvent, ...formData } : event
    );

    setEvents(updatedEvents);
    setIsEditDialogOpen(false);
    setSelectedEvent(null);
    setFormData({ status: 'Draft', category: 'Social' });
  };

  const openEditDialog = (event: Event) => {
    setSelectedEvent(event);
    setFormData(event);
    setIsEditDialogOpen(true);
  };

  const deleteEvent = (id: number) => {
    if (confirm('Are you sure you want to delete this event?')) {
      setEvents(events.filter(event => event.id !== id));
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Completed': return 'bg-green-100 text-green-700';
      case 'Ready': return 'bg-blue-100 text-blue-700';
      case 'Planning': return 'bg-yellow-100 text-yellow-700';
      case 'Draft': return 'bg-slate-100 text-slate-700';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  const upcomingEvents = events.filter(e => new Date(e.date) >= new Date() && e.status !== 'Completed');
  const completedEvents = events.filter(e => e.status === 'Completed');

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-semibold text-slate-900">Event Management</h2>
          <p className="text-slate-600 mt-1">Create and manage club events with automated task generation</p>
        </div>
        <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger asChild>
            <Button className="bg-gradient-to-r from-purple-600 to-blue-600">
              <Plus className="w-4 h-4 mr-2" />
              Add Event
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-purple-600" />
                Create New Event - Auto-Generate Tasks
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="bg-purple-50 border border-purple-200 rounded-lg p-3">
                <p className="text-sm text-purple-900 flex items-center gap-2">
                  <Sparkles className="w-4 h-4" />
                  Tasks will be automatically generated based on your event details!
                </p>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="col-span-2 space-y-2">
                  <Label htmlFor="event-name">Event Name *</Label>
                  <Input 
                    id="event-name" 
                    placeholder="e.g., Spring Fundraiser"
                    value={formData.name || ''}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="event-date">Event Date *</Label>
                  <Input 
                    id="event-date" 
                    type="date"
                    value={formData.date || ''}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="event-category">Category *</Label>
                  <Select value={formData.category} onValueChange={(value) => setFormData({ ...formData, category: value })}>
                    <SelectTrigger id="event-category">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {eventCategories.map(cat => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="event-budget">Budget ($) *</Label>
                  <Input 
                    id="event-budget" 
                    type="number" 
                    placeholder="2500"
                    value={formData.budget || ''}
                    onChange={(e) => setFormData({ ...formData, budget: Number(e.target.value) })}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="event-expected">Expected Attendees *</Label>
                  <Input 
                    id="event-expected" 
                    type="number" 
                    placeholder="100"
                    value={formData.expectedAttendees || ''}
                    onChange={(e) => setFormData({ ...formData, expectedAttendees: Number(e.target.value) })}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="event-status">Status</Label>
                  <Select value={formData.status} onValueChange={(value) => setFormData({ ...formData, status: value as Event['status'] })}>
                    <SelectTrigger id="event-status">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Draft">Draft</SelectItem>
                      <SelectItem value="Planning">Planning</SelectItem>
                      <SelectItem value="Ready">Ready</SelectItem>
                      <SelectItem value="Completed">Completed</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="event-venue">Venue (Optional)</Label>
                  <Input 
                    id="event-venue" 
                    placeholder="Student Center"
                    value={formData.venue || ''}
                    onChange={(e) => setFormData({ ...formData, venue: e.target.value })}
                  />
                </div>
                
                <div className="col-span-2 space-y-2">
                  <Label htmlFor="event-description">Description</Label>
                  <Textarea 
                    id="event-description" 
                    placeholder="Describe your event..."
                    value={formData.description || ''}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    rows={3}
                  />
                </div>
              </div>
              
              <Button onClick={handleAddEvent} className="w-full bg-gradient-to-r from-purple-600 to-blue-600">
                <Sparkles className="w-4 h-4 mr-2" />
                Create Event & Generate Tasks
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Automation Info */}
      <Card className="bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200">
        <CardContent className="p-4">
          <div className="flex items-start gap-3">
            <div className="bg-purple-100 p-2 rounded-lg">
              <Sparkles className="w-5 h-5 text-purple-600" />
            </div>
            <div>
              <h3 className="font-semibold text-purple-900 mb-1">Automated Event Management</h3>
              <p className="text-sm text-purple-800">
                When you create an event, we automatically generate 7+ tasks including venue booking, marketing, 
                logistics, and follow-up. Tasks are assigned to team members with smart due dates based on your event timeline.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-600">Total Events</p>
                <p className="text-2xl font-semibold text-slate-900 mt-1">{events.length}</p>
              </div>
              <Calendar className="w-8 h-8 text-slate-400" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-600">Upcoming</p>
                <p className="text-2xl font-semibold text-slate-900 mt-1">{upcomingEvents.length}</p>
              </div>
              <Clock className="w-8 h-8 text-blue-400" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-600">Completed</p>
                <p className="text-2xl font-semibold text-slate-900 mt-1">{completedEvents.length}</p>
              </div>
              <CheckCircle className="w-8 h-8 text-green-400" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-600">Total Budget</p>
                <p className="text-2xl font-semibold text-slate-900 mt-1">
                  ${events.reduce((sum, e) => sum + e.budget, 0).toLocaleString()}
                </p>
              </div>
              <DollarSign className="w-8 h-8 text-green-400" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Upcoming Events */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Calendar className="w-5 h-5 text-blue-600" />
            Upcoming Events
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {upcomingEvents.length === 0 ? (
              <p className="text-center text-slate-500 py-8">No upcoming events</p>
            ) : (
              upcomingEvents.map(event => (
                <div key={event.id} className="flex items-center justify-between p-4 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <h3 className="font-semibold text-slate-900">{event.name}</h3>
                      <Badge className={getStatusColor(event.status)}>{event.status}</Badge>
                      {event.autoGeneratedTasks && (
                        <Badge variant="outline" className="text-purple-600 border-purple-300">
                          <Sparkles className="w-3 h-3 mr-1" />
                          Auto Tasks
                        </Badge>
                      )}
                    </div>
                    <p className="text-sm text-slate-600 mb-2">{event.description}</p>
                    <div className="flex flex-wrap gap-4 text-sm text-slate-600">
                      <span className="flex items-center gap-1">
                        <Calendar className="w-4 h-4" />
                        {new Date(event.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                      </span>
                      <span className="flex items-center gap-1">
                        <DollarSign className="w-4 h-4" />
                        Budget: ${event.budget.toLocaleString()}
                      </span>
                      <span className="flex items-center gap-1">
                        <Users className="w-4 h-4" />
                        Expected: {event.expectedAttendees}
                      </span>
                      <Badge variant="outline">{event.category}</Badge>
                    </div>
                  </div>
                  <div className="flex gap-2 ml-4">
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={() => setQrCodeEvent(event)}
                      className="border-green-300 text-green-700 hover:bg-green-50"
                    >
                      <QrCode className="w-4 h-4" />
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => openEditDialog(event)}>
                      <Edit2 className="w-4 h-4" />
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => deleteEvent(event.id)}>
                      <Trash2 className="w-4 h-4 text-red-600" />
                    </Button>
                  </div>
                </div>
              ))
            )}
          </div>
        </CardContent>
      </Card>

      {/* Completed Events */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <CheckCircle className="w-5 h-5 text-green-600" />
            Completed Events
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {completedEvents.length === 0 ? (
              <p className="text-center text-slate-500 py-8">No completed events</p>
            ) : (
              completedEvents.map(event => {
                const metrics = calculateEventMetrics(event);
                return (
                  <div key={event.id} className="flex items-center justify-between p-4 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="font-semibold text-slate-900">{event.name}</h3>
                        <Badge className={getStatusColor(event.status)}>{event.status}</Badge>
                      </div>
                      <p className="text-sm text-slate-600 mb-2">{event.description}</p>
                      <div className="flex flex-wrap gap-4 text-sm">
                        <span className="text-slate-600">
                          <Calendar className="w-4 h-4 inline mr-1" />
                          {new Date(event.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                        </span>
                        {event.actualAttendees && (
                          <span className="font-medium text-green-600">
                            <Users className="w-4 h-4 inline mr-1" />
                            {event.actualAttendees} attendees ({metrics.successRate}%)
                          </span>
                        )}
                        {metrics.roi !== 'N/A' && (
                          <span className="font-medium text-purple-600">
                            <TrendingUp className="w-4 h-4 inline mr-1" />
                            ROI: {metrics.roi}x
                          </span>
                        )}
                        {typeof metrics.profit === 'number' && (
                          <span className="font-medium text-blue-600">
                            <DollarSign className="w-4 h-4 inline mr-1" />
                            Profit: ${metrics.profit.toLocaleString()}
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex gap-2 ml-4">
                      <Button variant="outline" size="sm" onClick={() => openEditDialog(event)}>
                        <Edit2 className="w-4 h-4" />
                      </Button>
                      <Button variant="outline" size="sm" onClick={() => deleteEvent(event.id)}>
                        <Trash2 className="w-4 h-4 text-red-600" />
                      </Button>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Event</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2 space-y-2">
                <Label htmlFor="edit-event-name">Event Name</Label>
                <Input 
                  id="edit-event-name" 
                  value={formData.name || ''}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-date">Event Date</Label>
                <Input 
                  id="edit-event-date" 
                  type="date"
                  value={formData.date || ''}
                  onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-status">Status</Label>
                <Select value={formData.status} onValueChange={(value) => setFormData({ ...formData, status: value as Event['status'] })}>
                  <SelectTrigger id="edit-event-status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Draft">Draft</SelectItem>
                    <SelectItem value="Planning">Planning</SelectItem>
                    <SelectItem value="Ready">Ready</SelectItem>
                    <SelectItem value="Completed">Completed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-budget">Budget ($)</Label>
                <Input 
                  id="edit-event-budget" 
                  type="number"
                  value={formData.budget || ''}
                  onChange={(e) => setFormData({ ...formData, budget: Number(e.target.value) })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-cost">Actual Cost ($)</Label>
                <Input 
                  id="edit-event-cost" 
                  type="number"
                  placeholder="Enter after event"
                  value={formData.actualCost || ''}
                  onChange={(e) => setFormData({ ...formData, actualCost: Number(e.target.value) })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-revenue">Revenue ($)</Label>
                <Input 
                  id="edit-event-revenue" 
                  type="number"
                  placeholder="Leave blank for free events"
                  value={formData.revenue || ''}
                  onChange={(e) => setFormData({ ...formData, revenue: Number(e.target.value) })}
                />
                <p className="text-xs text-slate-500">Optional - only enter for fundraising events</p>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-expected">Expected Attendees</Label>
                <Input 
                  id="edit-event-expected" 
                  type="number"
                  value={formData.expectedAttendees || ''}
                  onChange={(e) => setFormData({ ...formData, expectedAttendees: Number(e.target.value) })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-actual">Actual Attendees</Label>
                <Input 
                  id="edit-event-actual" 
                  type="number"
                  placeholder="Enter after event"
                  value={formData.actualAttendees || ''}
                  onChange={(e) => setFormData({ ...formData, actualAttendees: Number(e.target.value) })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="edit-event-venue">Venue</Label>
                <Input 
                  id="edit-event-venue"
                  value={formData.venue || ''}
                  onChange={(e) => setFormData({ ...formData, venue: e.target.value })}
                />
              </div>
              
              <div className="col-span-2 space-y-2">
                <Label htmlFor="edit-event-description">Description</Label>
                <Textarea 
                  id="edit-event-description"
                  value={formData.description || ''}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  rows={3}
                />
              </div>
            </div>
            
            {formData.status === 'Completed' && formData.actualCost && formData.revenue && formData.actualAttendees && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <h4 className="font-semibold text-green-900 mb-2">Auto-Calculated Metrics</h4>
                <div className="grid grid-cols-3 gap-4 text-sm">
                  <div>
                    <p className="text-green-600">ROI</p>
                    <p className="text-lg font-semibold text-green-900">
                      {(formData.revenue / formData.actualCost).toFixed(2)}x
                    </p>
                  </div>
                  <div>
                    <p className="text-green-600">Profit</p>
                    <p className="text-lg font-semibold text-green-900">
                      ${(formData.revenue - formData.actualCost).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <p className="text-green-600">Success Rate</p>
                    <p className="text-lg font-semibold text-green-900">
                      {((formData.actualAttendees / (formData.expectedAttendees || 1)) * 100).toFixed(0)}%
                    </p>
                  </div>
                </div>
              </div>
            )}
            
            <Button onClick={handleUpdateEvent} className="w-full">
              Update Event
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* QR Code Dialog */}
      <Dialog open={!!qrCodeEvent} onOpenChange={() => setQrCodeEvent(null)}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <QrCode className="w-5 h-5 text-green-600" />
              Event Check-In QR Code
            </DialogTitle>
          </DialogHeader>
          {qrCodeEvent && (
            <div className="space-y-4 py-4">
              <div className="text-center">
                <h3 className="font-semibold text-lg text-slate-900 mb-2">{qrCodeEvent.name}</h3>
                <p className="text-sm text-slate-600">
                  {new Date(qrCodeEvent.date).toLocaleDateString('en-US', { 
                    weekday: 'long',
                    month: 'long', 
                    day: 'numeric', 
                    year: 'numeric' 
                  })}
                </p>
              </div>

              {/* QR Code */}
              <div className="flex justify-center p-6 bg-white border-2 border-slate-200 rounded-lg">
                <QRCodeDisplay 
                  value={`${window.location.origin}/attendance/${qrCodeEvent.id}`}
                  size={256}
                />
              </div>

              {/* Instructions */}
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <h4 className="font-semibold text-green-900 mb-2 flex items-center gap-2">
                  <Sparkles className="w-4 h-4" />
                  Automated Attendance Tracking
                </h4>
                <ul className="text-sm text-green-800 space-y-1">
                  <li>• Attendees scan this QR code to check in</li>
                  <li>• Attendance is automatically tracked and saved</li>
                  <li>• View real-time check-in count on the attendance page</li>
                  <li>• Data syncs automatically to your event metrics</li>
                </ul>
              </div>

              {/* Check-in URL */}
              <div className="space-y-2">
                <Label>Check-In URL</Label>
                <div className="flex gap-2">
                  <Input 
                    value={`${window.location.origin}/attendance/${qrCodeEvent.id}`}
                    readOnly
                    className="font-mono text-sm"
                  />
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => {
                      navigator.clipboard.writeText(`${window.location.origin}/attendance/${qrCodeEvent.id}`);
                      alert('URL copied to clipboard!');
                    }}
                  >
                    Copy
                  </Button>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-2 gap-3 pt-2">
                <Button 
                  variant="outline"
                  onClick={() => window.open(`/attendance/${qrCodeEvent.id}`, '_blank')}
                  className="w-full"
                >
                  <ExternalLink className="w-4 h-4 mr-2" />
                  Open Check-In Page
                </Button>
                <Button 
                  onClick={() => {
                    // Download QR code as image
                    const canvas = document.querySelector('#qr-code-canvas') as HTMLCanvasElement;
                    if (canvas) {
                      const pngFile = canvas.toDataURL("image/png");
                      const downloadLink = document.createElement("a");
                      downloadLink.download = `${qrCodeEvent.name}-QRCode.png`;
                      downloadLink.href = pngFile;
                      downloadLink.click();
                    }
                  }}
                  className="w-full bg-gradient-to-r from-green-600 to-blue-600"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download QR Code
                </Button>
              </div>

              {/* Current Attendance */}
              <div className="bg-slate-50 rounded-lg p-4 text-center">
                <p className="text-sm text-slate-600 mb-1">Current Check-Ins</p>
                <p className="text-3xl font-semibold text-slate-900">
                  {(() => {
                    const stored = localStorage.getItem(`attendance-${qrCodeEvent.id}`);
                    const attendees = stored ? JSON.parse(stored) : [];
                    return attendees.length;
                  })()}
                </p>
                <p className="text-xs text-slate-500 mt-1">
                  Expected: {qrCodeEvent.expectedAttendees}
                </p>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}