export const DEMO_ORG_ID = 'duck-appreciation-marketing-club-demo'
export const DEMO_ORG_NAME = 'Duck Appreciation Marketing Club'

export interface DemoTask {
  id: number
  title: string
  description: string
  assignee: string
  dueDate: string
  priority: 'High' | 'Medium' | 'Low'
  status: 'To Do' | 'In Progress' | 'Completed'
  category: string
  team: string
}

export interface DemoEvent {
  id: number
  name: string
  date: string
  budget: number
  actualCost?: number
  revenue?: number
  expectedAttendees: number
  actualAttendees?: number
  status: 'Draft' | 'Planning' | 'Ready' | 'Completed'
  category: string
  description: string
  venue?: string
  autoGeneratedTasks?: boolean
}

export interface DemoBudgetCategory {
  id: number
  name: string
  allocated: number
  spent: number
  color: string
}

export interface DemoTransaction {
  id: number
  category: string
  description: string
  amount: number
  date: string
  type: 'expense' | 'income'
}

export const DEMO_TASKS: DemoTask[] = [
  {
    id: 1,
    title: 'Design Duck Facts Campaign Posters',
    description: 'Create a poster set for Barton Hall and Duffield promoting duck facts week.',
    assignee: 'Sarah Chen',
    dueDate: '2026-03-19',
    priority: 'High',
    status: 'In Progress',
    category: 'Marketing',
    team: 'Marketing',
  },
  {
    id: 2,
    title: 'Reserve Beebe Lake Info Booth',
    description: 'Coordinate with campus events to reserve booth space near Beebe Lake.',
    assignee: 'Mike Johnson',
    dueDate: '2026-03-17',
    priority: 'High',
    status: 'To Do',
    category: 'Events',
    team: 'Events',
  },
  {
    id: 3,
    title: 'Finalize Sponsor Packet for Feed Fund',
    description: 'Prepare the sponsor deck and pricing tiers for alumni outreach.',
    assignee: 'Alex Brown',
    dueDate: '2026-03-21',
    priority: 'Medium',
    status: 'To Do',
    category: 'Finance',
    team: 'Finance',
  },
  {
    id: 4,
    title: 'Post Event Recap on Instagram',
    description: 'Publish carousel from last weekend\'s duck walk and thank volunteers.',
    assignee: 'Emma Davis',
    dueDate: '2026-03-14',
    priority: 'Low',
    status: 'Completed',
    category: 'Communications',
    team: 'Marketing',
  },
]

export const DEMO_EVENTS: DemoEvent[] = [
  {
    id: 1,
    name: 'Beebe Lake Duck Walk',
    date: '2026-03-22',
    budget: 900,
    expectedAttendees: 80,
    status: 'Ready',
    category: 'Community Service',
    description: 'Campus guided walk focused on duck habitats and student clean-up.',
    venue: 'Beebe Lake',
    autoGeneratedTasks: true,
  },
  {
    id: 2,
    name: 'Duck Branding Workshop',
    date: '2026-04-02',
    budget: 650,
    expectedAttendees: 45,
    status: 'Planning',
    category: 'Educational',
    description: 'Hands-on workshop on campus storytelling and student marketing strategy.',
    venue: 'Duffield Hall 250',
    autoGeneratedTasks: true,
  },
  {
    id: 3,
    name: 'Fall Quack-a-thon Fundraiser',
    date: '2025-11-15',
    budget: 1200,
    actualCost: 1100,
    revenue: 3600,
    expectedAttendees: 120,
    actualAttendees: 132,
    status: 'Completed',
    category: 'Fundraising',
    description: 'Annual fundraiser supporting wildlife education initiatives.',
    venue: 'Ho Plaza',
    autoGeneratedTasks: true,
  },
]

export const DEMO_BUDGET_CATEGORIES: DemoBudgetCategory[] = [
  { id: 1, name: 'Events', allocated: 2500, spent: 1450, color: 'bg-blue-500' },
  { id: 2, name: 'Marketing', allocated: 1400, spent: 980, color: 'bg-purple-500' },
  { id: 3, name: 'Operations', allocated: 900, spent: 540, color: 'bg-green-500' },
  { id: 4, name: 'Outreach', allocated: 1100, spent: 620, color: 'bg-orange-500' },
]

export const DEMO_TRANSACTIONS: DemoTransaction[] = [
  { id: 1, category: 'Events', description: 'Beebe Lake permit and setup', amount: -420, date: '2026-03-04', type: 'expense' },
  { id: 2, category: 'Marketing', description: 'Poster printing run', amount: -260, date: '2026-03-06', type: 'expense' },
  { id: 3, category: 'Outreach', description: 'Alumni donation - Duck Fund', amount: 1400, date: '2026-03-07', type: 'income' },
  { id: 4, category: 'Operations', description: 'Volunteer supplies', amount: -180, date: '2026-03-09', type: 'expense' },
  { id: 5, category: 'Events', description: 'Workshop refreshments', amount: -210, date: '2026-03-11', type: 'expense' },
]

export function cloneDemoTasks() {
  return DEMO_TASKS.map((task) => ({ ...task }))
}

export function cloneDemoEvents() {
  return DEMO_EVENTS.map((event) => ({ ...event }))
}

export function cloneDemoBudgetCategories() {
  return DEMO_BUDGET_CATEGORIES.map((category) => ({ ...category }))
}

export function cloneDemoTransactions() {
  return DEMO_TRANSACTIONS.map((transaction) => ({ ...transaction }))
}
